server {
    listen ${PORT};
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    types {
        application/wasm wasm;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
